# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eny5351EQhd1q-7Fgb3Aux8GttjdPuAd
"""

!pip install --upgrade pip
!pip install streamlit pyngrok requests python-dotenv pandas python-dateutil geopy

# Cell 2 — write the Streamlit app (streamlit_app.py)
streamlit_code = r'''
import os, json, time
import streamlit as st
from datetime import datetime, timedelta
from dateutil import parser

# Optional: requests for calling CrewAI AMP
import requests

st.set_page_config(page_title="Travel Itinerary Planner (Colab POV)", layout="wide")
st.title("✈️ Travel Itinerary Planner — Prototype (Colab)")

with st.sidebar:
    st.header("Traveler preferences")
    name = st.text_input("Name", value="Traveler")
    destination = st.text_input("Destination (city / country)", value="Paris, France")
    start_date = st.date_input("Start date", value=datetime.now().date())
    trip_days = st.slider("Trip length (days)", 1, 14, 3)
    budget = st.number_input("Total budget (approx, in USD)", min_value=1, value=800)
    interests = st.multiselect("Interests", ["Museums","Food","History","Walking tours","Nightlife","Nature","Shopping","Beaches"], default=["Museums","Food"])
    include_maps = st.checkbox("Include map links / simple routes", value=True)
    use_real_crewai = st.checkbox("Use CrewAI AMP (requires API key + endpoint)", value=False)
    crewai_endpoint = st.text_input("CrewAI AMP kickoff URL (if using)", value="")
    crewai_api_key = st.text_input("CrewAI API key (if using)", value="", type="password")
    run_button = st.button("Generate itinerary")

def mock_run_crew(inputs):
    # Simple mock planner that builds an itinerary from interests
    destination = inputs["destination"]
    start = parser.isoparse(inputs["start_date"]).date()
    days = []
    for d in range(inputs["trip_days"]):
        day_date = (start + timedelta(days=d)).isoformat()
        acts = []
        # example pattern: morning attraction, lunch, afternoon walk, evening optional
        acts.append({"time":"09:00","title":f"Top {inputs['interests'][0]} spot in {destination}","duration":"2h","estimated_cost":20})
        acts.append({"time":"12:30","title":"Local lunch (recommendations)","duration":"1.5h","estimated_cost":18})
        if len(inputs['interests'])>1:
            acts.append({"time":"14:30","title":f"{inputs['interests'][1]} experience","duration":"2h","estimated_cost":10})
        acts.append({"time":"18:00","title":"Optional evening activity / local recommendations","duration":"2h","estimated_cost":0})
        days.append({"date":day_date,"summary":f"Day {d+1}: mix of {', '.join(inputs['interests'][:2])}","activities":acts})
    plan = {"traveler":inputs["traveler_name"],"destination":destination,"start_date":inputs["start_date"],"days":days,"estimated_total":sum(a["estimated_cost"] for day in days for a in day["activities"])}
    return plan

def run_crew_via_amp(inputs, endpoint, api_key):
    # Example HTTP template — adapt per CrewAI AMP docs
    # This function expects the AMP endpoint to accept a JSON payload:
    # { "inputs": {...}, "crew": "travel-itinerary-crew" } and respond with a kickoff id or final plan.
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    payload = {"crew":"travel-itinerary-crew", "inputs": inputs}
    resp = requests.post(endpoint, headers=headers, json=payload, timeout=60)
    resp.raise_for_status()
    return resp.json()

if run_button:
    st.info("Composing inputs and running planner (mock or CrewAI)...")
    inputs = {
        "traveler_name": name,
        "destination": destination,
        "start_date": start_date.isoformat(),
        "trip_days": trip_days,
        "budget_usd": float(budget),
        "interests": interests,
        "include_maps": include_maps
    }

    try:
        if use_real_crewai and crewai_endpoint and crewai_api_key:
            st.write("Calling CrewAI AMP endpoint...")
            result = run_crew_via_amp(inputs, crewai_endpoint, crewai_api_key)
            # Expect result to include final plan; if Kickoff ID returned, you'd poll or receive webhook.
            st.success("CrewAI responded — parsing plan (this demo expects final plan in response).")
            plan = result.get("plan") or result  # adapt to your AMP response format
        else:
            st.write("Using local mock planner for quick demo.")
            plan = mock_run_crew(inputs)

        st.session_state['last_plan'] = plan
    except Exception as e:
        st.error(f"Planner failed: {e}")

if 'last_plan' in st.session_state and st.session_state['last_plan']:
    plan = st.session_state['last_plan']
    st.header(f\"Plan for {plan.get('traveler','Traveler')} — {plan.get('destination')}\")
    st.markdown(f\"**Start:** {plan['start_date']}  —  **Estimated total:** ${plan.get('estimated_total','TBD')}\")
    for day in plan["days"]:
        with st.expander(f\"{day['date']} — {day['summary']}\"):
            for a in day["activities"]:
                line = f\"{a['time']} — **{a['title']}** ({a['duration']}) — Est. ${a['estimated_cost']}\"
                # include a maps link if requested — simple Google Maps search
                if include_maps:
                    q = f\"{a['title']} {plan['destination']}\"
                    maps = f\"https://www.google.com/maps/search/{requests.utils.quote(q)}\"
                    line += f\"  [map]({maps})\"
                st.markdown(line, unsafe_allow_html=True)

    st.download_button(\"Download itinerary (JSON)\", data=json.dumps(plan, indent=2), file_name=\"itinerary.json\", mime=\"application/json\")
    st.caption(\"Demo: replace mock_run_crew with real CrewAI AMP calls and parse the crew's output format.\")
'''
open('streamlit_app.py','w').write(streamlit_code)
print("Wrote streamlit_app.py")

# Cell 3 — install pyngrok and set up an ngrok authtoken (replace with your token if you have one)
!pip install pyngrok
from pyngrok import ngrok, conf
# Optionally set your ngrok auth token for more stable tunnels:
# conf.get_default().auth_token = "YOUR_NGROK_AUTHTOKEN"

# Cell 4 — run Streamlit and expose via ngrok
import threading, time, os
from pyngrok import ngrok

ngrok.set_auth_token("35cAjCU8DguaVJk9nruWzaaraSp_2T4rvuhpAPacmZhBcMCmg")

# Kill previous tunnels
ngrok.kill()

def run_streamlit():
    os.system("streamlit run streamlit_app.py --server.port 8501")

thread = threading.Thread(target=run_streamlit, daemon=True)
thread.start()

time.sleep(5)

public_url = ngrok.connect(8501, "http")
print("🚀 Streamlit App URL:", public_url)

# Cell 5 — prompt templates (example strings you can pass to LLMs/agents)
research_prompt = """
You are ResearchAgent. Input: destination={destination}, interests={interests}.
Task: produce a ranked list (top 8) of attractions/POIs with short descriptions, recommended visit duration, best time of day to visit, approximate opening hours, and suggested priority.
Return JSON: [{"name": "...", "desc":"...", "duration":"2h", "best_time":"morning", "opening":"09:00-17:00", "priority":1}, ...]
"""

cost_prompt = """
You are CostAgent. Input: attraction list, traveler profile (budget, travel style).
Task: estimate per-day costs: accommodation_range, food_range, transit_per_day, attraction_fees (per-item).
Return JSON with numeric estimates in USD and brief rationale.
"""

itinerary_prompt = """
You are ItineraryAgent. Input: attractions (ranked), trip_days, start_date, traveler preferences.
Task: schedule day-by-day plan with times, travel hints between POIs, and total estimated daily cost.
Return JSON plan with keys: start_date, days:[{date, activities:[{time,title,duration,estimated_cost,notes}]}], total_estimated_cost
"""
print("Prompt templates ready. Use them inside your CrewAI agent tasks.")

!apt-get install git

!git config --global user.email "YOUR_EMAIL@example.com"
!git config --global user.name "Your Name"

!git clone https://github.com/YOUR_USERNAME/travel-itinerary-ai-agent.git

!ls travel-itinerary-ai-agent

!cp streamlit_app.py travel-itinerary-ai-agent/
!cp crew_setup.py travel-itinerary-ai-agent/

!cp -r your_folder/* travel-itinerary-ai-agent/

# Commented out IPython magic to ensure Python compatibility.
# %cd travel-itinerary-ai-agent
!git add .
!git commit -m "Initial commit: Travel Itinerary Planner AI Agent"
!git push https://YOUR_USERNAME:YOUR_TOKEN@github.com/YOUR_USERNAME/travel-itinerary-ai-agent.git

!git push https://github.com/Atharv-Deepak-Yadav/travel-itinerary-ai-agent

!pip install streamlit pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("35cAjCU8DguaVJk9nruWzaaraSp_2T4rvuhpAPacmZhBcMCmg")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import requests
# 
# st.title("AI Travel Itinerary Planner 🌍✈️")
# 
# destination = st.text_input("Enter Destination")
# budget = st.number_input("Enter Budget", min_value=0)
# interests = st.text_area("Your Interests (e.g., beaches, temples, nightlife)")
# 
# if st.button("Generate Plan"):
#     response = requests.post(
#         "http://localhost:8000/plan",
#         json={
#             "destination": destination,
#             "budget": budget,
#             "interests": interests
#         }
#     )
#     st.write("### Your Travel Plan")
#     st.write(response.json())
#

!python main.py

!streamlit run app.py & ngrok http 8501
